# Corrected Netlify Configuration for Epic Resume
# Fixed: Removed Python dependency installation trigger
# Fixed: Corrected build command

[build]
  publish = "dist"
  command = "npm run build"  # Changed from "npm run build:production"

# Environment variables
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# SPA Redirect - Essential for single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization for assets
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# PWA Headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# Error handling
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404
